version: '3.8'

services:

    # Focus component
    jicofo:
        image: jitsi/jicofo:latest
        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
          #placement:
          #  constraints:
          #    - node.hostname == demo2

                #healthcheck:
                #test: curl 127.0.0.1:8888/about/health || exit 1
                #interval: 5s
                #timeout: 5s
                #retries: 3
                #start_period: 3s
        environment:
            AUTH_TYPE: internal
            BRIDGE_AVG_PARTICIPANT_STRESS:
            BRIDGE_STRESS_THRESHOLD:
            ENABLE_AUTH: 1
            ENABLE_AUTO_OWNER: "true"
            # enable/disable video codec
            ENABLE_CODEC_VP8: "true"
            ENABLE_CODEC_VP9: "true"
            ENABLE_CODEC_H264: "true"
            ENABLE_OCTO: 0
            ENABLE_RECORDING: 0
            ENABLE_SCTP: "false"
            ENABLE_AUTO_LOGIN:
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_REQUEST_RETRIES:
            JIBRI_PENDING_TIMEOUT: 90
            JICOFO_AUTH_USER: focus
            JICOFO_AUTH_PASSWORD: CHANGE_HERE
            # Bridge healthcheck
            JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS: "true"
            JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT:
            JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT:
            # internal healthcheck
            JICOFO_ENABLE_HEALTH_CHECKS: "true"
            JICOFO_SHORT_ID: 1
            JICOFO_RESERVATION_ENABLED:
            JICOFO_RESERVATION_REST_BASE_URL:
            JIGASI_BREWERY_MUC: jigasibrewery
            JIGASI_SIP_URI:
            JVB_BREWERY_MUC: jvbbrewery
            # Bridge config
            MAX_BRIDGE_PARTICIPANTS:
            OCTO_BRIDGE_SELECTION_STRATEGY: SplitBridgeSelectionStrategy #IntraRegionBridgeSelectionStrategy #SingleBridgeSelectionStrategy
            SENTRY_DSN: "${JICOFO_SENTRY_DSN:-0}"
            SENTRY_ENVIRONMENT:
            SENTRY_RELEASE:
            TZ: Asia/Kolkata      
            XMPP_AUTH_DOMAIN: auth.meet.jitsi
            XMPP_DOMAIN: meet.jitsi
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
            XMPP_SERVER: xmpp.meet.jitsi
            XMPP_MUC_DOMAIN: muc.meet.jitsi
        depends_on:
            - prosody
        volumes:
            - ${CONFIG}/jicofo:/config
        ports:
            - target: 8888
              published: 8888
        networks:
            jitsi:
# Custom network so all services can communicate using a FQDN
networks:
  jitsi:
    external: true
    name: jitsi