#!/bin/sh

inotifywait -m /tmp/transcripts/ -m -r -e create -e moved_to |
    while read dir action file; do
        echo "The file '$file' appeared in directory '$dir' via '$action'"
        transcriptfilename=$dir$file
	if test -f "$transcriptfilename"; then
                   if [ "${transcriptfilename##*.}" = "txt" ] && [ "${transcriptfilename##*.}" != "transcription" ] ; then
  		      echo "$transcriptfilename exists."
                      nohup /rclone.sh $dir &
                      wait
		   fi

        fi
	echo "transcription file recieved"
        echo "done file transfer"
done
