services:
    tempo:
        image: grafana/tempo:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        command:
            - -config.file=/etc/tempo/tempo.yaml
        volumes:
            - ./tracing/tempo/:/etc/tempo/
        ports:
            - "3200:3200"
        networks:
            meet.jitsi:


    alloy:
        image: grafana/alloy:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        volumes:
            - ./tracing/alloy/:/etc/alloy/
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
        environment:
            - ALLOY_OTLP_UPSTREAM=tempo:4317
        ports:
            - "12345:12345"
            - "4317:4317"
        depends_on:
            - tempo
        networks:
            meet.jitsi:
