services:
    whiteboard:
        image: jitsi/excalidraw-backend:2026.3.0
        restart: ${RESTART_POLICY:-unless-stopped}
        depends_on:
            - web
        networks:
            meet.jitsi:
              aliases:
                  - whiteboard.meet.jitsi
