#!/command/with-contenv bash
set -euo pipefail

if [[ ! -f /etc/saslauthd.conf ]]; then
    tpl /defaults/saslauthd.conf > /etc/saslauthd.conf
    mkdir -p /var/run/saslauthd
    chmod 777 /var/run/saslauthd
    adduser prosody sasl
    echo >> /etc/ldap/ldap.conf "TLS_REQCERT allow"
fi

if [[ ! -d /config/data ]]; then
    mkdir -p /config/data
    chmod 750 /config/data
fi

if [[ "$(stat -c %U /config)" != "prosody" ]]; then
    chown -R prosody:prosody /config
fi

if [[ "$(stat -c %U /prosody-plugins)" != "prosody" ]]; then
    chown -R prosody:prosody /prosody-plugins
fi

if [[ "$(stat -c %U /prosody-plugins-custom)" != "prosody" ]]; then
    chown -R prosody:prosody /prosody-plugins-custom
fi

PROSODY_CFG="/config/prosody.cfg.lua"
JITSI_CFG="/config/conf.d/jitsi-meet.cfg.lua"

cp -r /defaults/* /config
tpl /defaults/prosody.cfg.lua > "${PROSODY_CFG}"
tpl /defaults/conf.d/jitsi-meet.cfg.lua > "${JITSI_CFG}"

if [[ -z "${JICOFO_AUTH_PASSWORD:-}" ]]; then
    echo 'FATAL ERROR: Jicofo auth password must be set' 1>&2
    exit 1
fi

prosodyctl --config "${PROSODY_CFG}" register "${JICOFO_AUTH_USER}" "${XMPP_AUTH_DOMAIN}" "${JICOFO_AUTH_PASSWORD}"
prosodyctl --config "${PROSODY_CFG}" mod_roster_command subscribe focus."${XMPP_DOMAIN}" "${JICOFO_AUTH_USER}"@"${XMPP_AUTH_DOMAIN}"

if [[ -z "${JVB_AUTH_PASSWORD}" ]]; then
    echo 'FATAL ERROR: JVB auth password must be set' 1>&2
    exit 1
fi

OLD_JVB_AUTH_PASSWORD="passw0rd"
if [[ "${JVB_AUTH_PASSWORD}" == "${OLD_JVB_AUTH_PASSWORD}" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README' 1>&2
    exit 1
fi

prosodyctl --config "${PROSODY_CFG}" register "${JVB_AUTH_USER}" "${XMPP_AUTH_DOMAIN}" "${JVB_AUTH_PASSWORD}"

if [[ -n "${JIBRI_XMPP_USER}" ]] && [[ -n "${JIBRI_XMPP_PASSWORD}" ]]; then
    OLD_JIBRI_XMPP_PASSWORD="passw0rd"
    if [[ "${JIBRI_XMPP_PASSWORD}" == "${OLD_JIBRI_XMPP_PASSWORD}" ]]; then
        echo 'FATAL ERROR: Jibri auth password must be changed, check the README' 1>&2
        exit 1
    fi
    prosodyctl --config "${PROSODY_CFG}" register "${JIBRI_XMPP_USER}" "${XMPP_AUTH_DOMAIN}" "${JIBRI_XMPP_PASSWORD}"
fi

if [[ -n "${JIBRI_RECORDER_USER}" ]] && [[ -n "${JIBRI_RECORDER_PASSWORD}" ]]; then
    OLD_JIBRI_RECORDER_PASSWORD="passw0rd"
    if [[ "${JIBRI_RECORDER_PASSWORD}" == "${OLD_JIBRI_RECORDER_PASSWORD}" ]]; then
        echo 'FATAL ERROR: Jibri recorder password must be changed, check the README' 1>&2
        exit 1
    fi
    prosodyctl --config "${PROSODY_CFG}" register "${JIBRI_RECORDER_USER}" "${XMPP_RECORDER_DOMAIN}" "${JIBRI_RECORDER_PASSWORD}"
fi

if [[ -n "${JIGASI_XMPP_USER}" ]] && [[ -n "${JIGASI_XMPP_PASSWORD}" ]]; then
    OLD_JIGASI_XMPP_PASSWORD=passw0rd
    if [[ "${JIGASI_XMPP_PASSWORD}" == "${OLD_JIGASI_XMPP_PASSWORD}" ]]; then
        echo 'FATAL ERROR: Jigasi auth password must be changed, check the README' 1>&2
        exit 1
    fi
    prosodyctl --config "${PROSODY_CFG}" register "${JIGASI_XMPP_USER}" "${XMPP_AUTH_DOMAIN}" "${JIGASI_XMPP_PASSWORD}"
fi

mkdir -p /config/certs

if [[ ! -f /config/certs/"${XMPP_DOMAIN}".crt ]]; then
    # echo for using all default values
    echo | prosodyctl --config "${PROSODY_CFG}" cert generate "${XMPP_DOMAIN}"
fi

if [[ ! -f /config/certs/"${XMPP_AUTH_DOMAIN}".crt ]]; then
    # echo for using all default values
    echo | prosodyctl --config "${PROSODY_CFG}" cert generate "${XMPP_AUTH_DOMAIN}"
fi

# certs will be created in /config/data
mv /config/data/*.{crt,key} /config/certs/ || true
rm -f /config/data/*.cnf
