#!/bin/bash
set -euo pipefail

# get the value from the secret passed to the container
function _process_secret() {
    local -r file="$(realpath "${1}")"
    local -r env_dir="$(realpath "${2}")"
    local -r name="$(basename "${file}")"
    local -r env_path="${env_dir}/${name}"

    cat "${file}" > "${env_path}"
}

function _load_secrets() {
    local -r env_dir="/run/s6/container_environment"

    [[ -d "${env_dir}" ]] || {
        ret=${?}
        echo "ERROR: directory: '${env_dir}' doesn't exist." 1>&2
        echo "ERROR: please ensure you have s6-overlay installed." 1>&2
        return $ret
    }

    # make all secrets available as environment variables
    for file in /run/secrets/*; do
        [[ -f "${file}" ]] || {
            echo "INFO: skipping file '${file}'"
            continue
        }
        _process_secret "${file}" "${env_dir}" || {
            ret=${?}
            echo "ERROR: file: '${file}' could not be processes." 1>&2
            echo "ERROR: please confirm permissions." 1>&2
            return $ret
        }
    done

    return ${?}
}

_load_secrets
declare -i rt="${?}"

sync

exit ${rt}
