#!/usr/bin/with-contenv bash

if [[ ! -f /config/sip-communicator.properties ]]; then
    tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
fi

if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi

mkdir -pm777 /tmp/transcripts
chown jigasi:jitsi /tmp/transcripts
