#!/command/with-contenv bash

[ -f /run/ca/env ] && . /run/ca/env

JAVA_SYS_PROPS="-Djava.util.logging.config.file=/run/jicofo/config/logging.properties -Dconfig.file=/run/jicofo/config/jicofo.conf $CUSTOM_CA_JAVA_PROPS"
DAEMON=/usr/share/jicofo/jicofo.sh
DAEMON_DIR=/usr/share/jicofo/

JICOFO_CMD="exec $DAEMON"

[ -n "$JICOFO_LOG_FILE" ] && JICOFO_CMD="$JICOFO_CMD 2>&1 | tee -a $JICOFO_LOG_FILE"

exec /bin/bash -c "cd $DAEMON_DIR; JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" $JICOFO_CMD"
