#!/command/with-contenv bash

[ -f /run/ca/env ] && . /run/ca/env

JAVA_SYS_PROPS="-Djava.util.logging.config.file=/run/jigasi/config/logging.properties -Djava.io.tmpdir=/run/jigasi/tmp -Djna.tmpdir=/run/jigasi/tmp $JAVA_CUSTOM_CA_PROPS"

DAEMON=/usr/share/jigasi/jigasi.sh
DAEMON_OPTS="--nocomponent=true --configdir=/run/jigasi --configdirname=config --min-port=${JIGASI_PORT_MIN:-20000} --max-port=${JIGASI_PORT_MAX:-20050}"

JIGASI_CMD="JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" exec $DAEMON $DAEMON_OPTS"
[ -n "$JIGASI_LOG_FILE" ] && JIGASI_CMD="$JIGASI_CMD 2>&1 | tee -a $JIGASI_LOG_FILE"

exec /bin/bash -c "$JIGASI_CMD"
