#!/bin/sh
# ** (c) 2020 TosoBoso - library for Jitsi-Meet in Docker container
# shellcheck disable=SC2034
RELEASE="Stable"
PKG_NAME="Jitsi-Meet"
PKG_SHORT="jitsi"
DHUB_URL="https://hub.docker.com/u/jitsi"
DREPO_URL="https://registry.hub.docker.com/v2/repositories/jitsi"
GREPO_URL="https://raw.githubusercontent.com/jitsi/docker-jitsi-meet/master"
ETC_REPO_FILES="env.example docker-compose.yml jibri.yml jigasi.yml etherpad.yml"
# name, tag and size on docker images to be loaded via synology gui helper
IMGS_BASE_SHORT="web prosody jicofo jvb"
IMGS_BASE_TAG=(latest latest latest latest)
IMGS_BASE_SIZE=(185 41 137 122)
IMGS_XTRA_SHORT="etherpad jibri jigasi"
IMGS_XTRA_TAG=(latest latest latest)
IMGS_XTRA_SIZE=(83 395 154)
# etc-sub-dirs to re re-created each init and monuted to containers; this can cahnge with future releases
ETC_SUB_DIRS="web web/letsencrypt transcripts prosody prosody/config prosody/prosody-plugins-custom jicofo jvb jigasi jibri"
IPINFO_URL="ipinfo.io/ip"
# load language file (csy dan, enu fre ger hun ita jpn krn nld nor plk ptg rus spn sve trk)
SCRIPT_DIR=$(dirname "$0")
# when called via softlink in non gui mode set script-dir and dsm laguage updated earlier by postinst
[ -f "$SCRIPT_DIR"/lib  ] || SCRIPT_DIR=/var/packages/"$PKG_NAME"/scripts
[ -n "$SYNOPKG_DSM_LANGUAGE" ] || SYNOPKG_DSM_LANGUAGE=enu
LANG_FILE="$SCRIPT_DIR"/lang/"$SYNOPKG_DSM_LANGUAGE"
if [ -f "${LANG_FILE}" ]; then
    . "${LANG_FILE}"
else
    . "$SCRIPT_DIR"/lang/enu
fi
