objects:
- <<: (( merge ))
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jitsi-config
  data:
    TZ: ${TZ}
    ENABLE_AUTH: ${ENABLE_AUTH}
    ENABLE_GUESTS: ${ENABLE_GUESTS}
    ENABLE_LETSENCRYPT: ${ENABLE_LETSENCRYPT}
    ENABLE_HTTP_REDIRECT: ${ENABLE_HTTP_REDIRECT}
    DISABLE_HTTPS: ${DISABLE_HTTPS}
    LETSENCRYPT_DOMAIN: ${HOSTNAME}
    LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    XMPP_DOMAIN: ${HOSTNAME}
    XMPP_AUTH_DOMAIN: "auth.${HOSTNAME}"
    XMPP_GUEST_DOMAIN: "guest.${HOSTNAME}"
    XMPP_MUC_DOMAIN: "muc.${HOSTNAME}"
    XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.${HOSTNAME}"
    XMPP_MODULES: ${XMPP_MODULES}
    XMPP_MUC_MODULES: ${XMPP_MUC_MODULES}
    XMPP_INTERNAL_MUC_MODULES: ${XMPP_INTERNAL_MUC_MODULES}
    JVB_BREWERY_MUC: ${JVB_BREWERY_MUC}
    JVB_TCP_HARVESTER_DISABLED: ${JVB_TCP_HARVESTER_DISABLED}
    JVB_STUN_SERVERS: ${JVB_STUN_SERVERS}
    JVB_ENABLE_APIS: ${JVB_ENABLE_APIS}
    JIGASI_SIP_URI: ${JIGASI_SIP_URI}
    JIGASI_SIP_SERVER: ${JIGASI_SIP_SERVER}
    JIGASI_SIP_PORT: ${JIGASI_SIP_PORT}
    JIGASI_SIP_TRANSPORT: ${JIGASI_SIP_TRANSPORT}
    JIGASI_BREWERY_MUC: ${JIGASI_BREWERY_MUC}
    JIGASI_PORT_MIN: ${JIGASI_PORT_MIN}
    JIGASI_PORT_MAX: ${JIGASI_PORT_MAX}
    JIGASI_ENABLE_SDES_SRTP: ${JIGASI_ENABLE_SDES_SRTP}
    JIGASI_SIP_KEEP_ALIVE_METHOD: ${JIGASI_SIP_KEEP_ALIVE_METHOD}
    JIGASI_HEALTH_CHECK_SIP_URI: ${JIGASI_HEALTH_CHECK_SIP_URI}
    JIGASI_HEALTH_CHECK_INTERVAL: ${JIGASI_HEALTH_CHECK_INTERVAL}
    JWT_APP_ID: ${JWT_APP_ID}
    JWT_ACCEPTED_ISSUERS: ${JWT_ACCEPTED_ISSUERS}
    JWT_ACCEPTED_AUDIENCES: ${JWT_ACCEPTED_AUDIENCES}
    LDAP_URL: ${LDAP_URL}
    LDAP_BASE: ${LDAP_BASE}
    LDAP_FILTER: ${LDAP_FILTER}
    LDAP_AUTH_METHOD: ${LDAP_AUTH_METHOD}
    LDAP_VERSION: ${LDAP_VERSION}
    LDAP_USE_TLS: ${LDAP_USE_TLS}
    LDAP_TLS_CIPHERS: ${LDAP_TLS_CIPHERS}
    LDAP_TLS_CHECK_PEER: ${LDAP_TLS_CHECK_PEER}
    LDAP_TLS_CACERT_FILE: ${LDAP_TLS_CACERT_FILE}
    LDAP_TLS_CACERT_DIR: ${LDAP_TLS_CACERT_DIR}
