objects:
- <<: (( merge ))
- apiVersion: v1
  kind: Secret
  metadata:
    name: jitsi-secret
  stringData:
    JICOFO_COMPONENT_SECRET: ${JICOFO_COMPONENT_SECRET}
    JICOFO_AUTH_USER: ${JICOFO_AUTH_USER}
    JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
    JVB_AUTH_USER: ${JVB_AUTH_USER}
    JVB_AUTH_PASSWORD: ${JVB_AUTH_PASSWORD}
    JIGASI_SIP_PASSWORD: ${JIGASI_SIP_PASSWORD}
    JIGASI_XMPP_USER: ${JIGASI_XMPP_USER}
    JIGASI_XMPP_PASSWORD: ${JIGASI_XMPP_PASSWORD}
    JWT_APP_SECRET: ${JWT_APP_SECRET}
    LDAP_BINDDN: ${LDAP_BINDDN}
    LDAP_BINDPW: ${LDAP_BINDPW}
