apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  namespace: default
data:
   JICOFO_COMPONENT_SECRET: {{ .Values.jicofo.secret }}
   JICOFO_AUTH_PASSWORD: {{ .Values.jicofo.password }}
   JVB_AUTH_PASSWORD: {{ .Values.jvb.password }}
