apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.fullname" . }}-prosody
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "jitsi-meet.fullname" . }}-prosody
  template:
    metadata:
      labels:
        app: {{ include "jitsi-meet.fullname" . }}-prosody
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "jitsi-meet.fullname" . }}-prosody
          image: {{ .Values.prosody.image.repository }}
          imagePullPolicy: {{ .Values.prosody.image.pullPolicy }}
          ports:
          - containerPort: 5222
          - containerPort: 5280
          - containerPort: 5347
          env:
          - name: JWT_APP_ID
            value: {{ .Values.prosody.jwt.id }}
          - name: JWT_APP_SECRET
            value: {{ .Values.prosody.jwt.secret }}
{{- with .Values.prosody.envs }}
{{ tpl . $ | indent 10 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}