{
 "title": "rtcstats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtcstats_session_count[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(rtcstats_session_error_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rtcstats_websocket_connections", "legendFormat": "__auto" },
    {
     "expr": "rate(rtcstats_websocket_connection_error[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dump Size Bytes Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(rtcstats_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(jvb_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(jicofo_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(jibri_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(jigasi_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(unknown_dump_size_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rtcstats_disk_queue_size", "legendFormat": "__auto" }
   ]
  }
 ]
}