apiVersion: v1
kind: Template
metadata:
  name: jitsi
objects: (( merge ))
parameters:
#
# Basic configuration options
#
- name: HOSTNAME
  required: true
- name: TZ
  displayName: Timezone
  required: true
- name: LOG_LEVEL


#
# HTTPS configuration
#
- name: DISABLE_HTTPS
- name: ENABLE_HTTP_REDIRECT


#
# Authentication configuration
#
- name: ENABLE_AUTH
- name: AUTH_TYPE
- name: ENABLE_GUESTS

- name: JWT_APP_ID
- name: JWT_APP_SECRET
- name: JWT_ACCEPTED_ISSUERS
- name: JWT_ACCEPTED_AUDIENCES
- name: JWT_ASAP_KEYSERVER
- name: JWT_ALLOW_EMPTY
- name: JWT_AUTH_TYPE
- name: JWT_TOKEN_AUTH_MODULE

- name: LDAP_URL
- name: LDAP_BASE
- name: LDAP_BINDDN
- name: LDAP_BINDPW
- name: LDAP_FILTER
- name: LDAP_AUTH_METHOD
- name: LDAP_VERSION
- name: LDAP_USE_TLS
- name: LDAP_TLS_CIPHERS
- name: LDAP_TLS_CHECK_PEER
- name: LDAP_TLS_CACERT_FILE
- name: LDAP_TLS_CACERT_DIR


#
# A comma separated list of APIs to enable when the JVB is started. The default is none.
# See https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md for more information
#
- name: JVB_ENABLE_APIS
  required: true


#
# Advanced configuration options
#
- name: JVB_PORT
  required: true
- name: JVB_TCP_HARVESTER_DISABLED
  required: true
- name: JVB_TCP_PORT
  required: true
- name: JVB_BREWERY_MUC
  required: true
- name: JVB_AUTH_USER
  required: true
- name: JVB_AUTH_PASSWORD
  required: true
- name: JVB_STUN_SERVERS
  required: true


- name: JICOFO_COMPONENT_SECRET
  required: true
- name: JICOFO_AUTH_USER
  required: true
- name: JICOFO_AUTH_PASSWORD
  required: true


- name: GLOBAL_CONFIG
- name: GLOBAL_MODULES
- name: XMPP_MODULES
- name: XMPP_MUC_MODULES
- name: XMPP_INTERNAL_MUC_MODULES


#
# Jigasi configuration options (needed for SIP gateway support)
#
- name: JIGASI_XMPP_USER
  required: true
- name: JIGASI_XMPP_PASSWORD
  required: true
- name: JIGASI_BREWERY_MUC
  required: true
- name: JIGASI_PORT_MIN
  required: true
- name: JIGASI_PORT_MAX
  required: true
- name: JIGASI_HEALTH_CHECK_SIP_URI
  required: true
- name: JIGASI_SIP_PASSWORD
  required: true
- name: JIGASI_SIP_SERVER
  required: true
- name: JIGASI_SIP_PORT
  required: true
- name: JIGASI_SIP_TRANSPORT
  required: true
- name: JIGASI_ENABLE_SDES_SRTP
- name: JIGASI_SIP_KEEP_ALIVE_METHOD
- name: JIGASI_HEALTH_CHECK_SIP_URI
- name: JIGASI_HEALTH_CHECK_INTERVAL


#
# Transcription
#
- name: ENABLE_TRANSCRIPTIONS
- name: JIGASI_TRANSCRIBER_RECORD_AUDIO
- name: JIGASI_TRANSCRIBER_SEND_TXT
- name: JIGASI_TRANSCRIBER_ADVERTISE_URL
- name: GC_PROJECT_ID
- name: GC_PRIVATE_KEY_ID
- name: GC_PRIVATE_KEY
- name: GC_CLIENT_EMAIL
- name: GC_CLIENT_ID
- name: GC_CLIENT_CERT_URL


#
# Let's Encrypt configuration
#
- name: ENABLE_LETSENCRYPT
- name: LETSENCRYPT_EMAIL
