#!/command/with-contenv bash
set -euo pipefail

if [[ -z "${JVB_AUTH_PASSWORD:-}" ]]; then
    echo 'FATAL ERROR: JVB auth password must be set' 1>&2
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "${JVB_AUTH_PASSWORD}" == "${OLD_JVB_AUTH_PASSWORD}" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README' 1>&2
    exit 1
fi

# On environments like Swarm the IP address used by the default gateway need not be
# the one used for inter-container traffic. Use that one for our fallback ID.
XMPP_SERVER_IP="$(dig +short +search "${XMPP_SERVER}")"
JVB_WS_SERVER_ID_FALLBACK=$(ip route get "${XMPP_SERVER_IP}" | grep -oP '(?<=src ).*' | awk '{ print $1 }')
export JVB_WS_SERVER_ID_FALLBACK
set-contenv JVB_WS_SERVER_ID_FALLBACK


# Local IP for the ice4j mapping harvester.
LOCAL_ADDRESS=$(ip route get 1 | grep -oP '(?<=src ).*' | awk '{ print $1 }')
export LOCAL_ADDRESS
set-contenv LOCAL_ADDRESS

[[ "${SENTRY_RELEASE:-}" ]] || {
    SENTRY_RELEASE="$(apt-cache policy jitsi-videobridge2 | sed -n '/Installed/p' | sed -e 's/[^:]*: //')"
}
export SENTRY_RELEASE
set-contenv SENTRY_RELEASE

if [[ -f /config/custom-sip-communicator.properties ]]; then
    cat /config/custom-sip-communicator.properties > /config/sip-communicator.properties
fi

tpl /defaults/logging.properties > /config/logging.properties
tpl /defaults/jvb.conf > /config/jvb.conf

chown -R jvb:jitsi /config
