#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{nginx/site-confs,keys} \
	/run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# copy config files
if [[ ! -f /config/nginx/nginx.conf ]]; then
	cp /defaults/nginx.conf /config/nginx/nginx.conf
fi

if [[ ! -f /config/nginx/site-confs/default ]]; then
	cp /defaults/default /config/nginx/site-confs/default
	sed -i \
	    -e "s,\${XMPP_DOMAIN},$XMPP_DOMAIN,g" \
	    -e "s,\${XMPP_BOSH_URL_BASE},$XMPP_BOSH_URL_BASE,g" \
	    /config/nginx/site-confs/default
fi

if [[ ! -f /config/config.js ]]; then
	cp /defaults/config.js /config/config.js
	sed -i "s/jitsi-meet.example.com/$XMPP_DOMAIN/g" /config/config.js
fi
