PUBLIC_URL=${PUBLIC_URL}
ENABLE_LETSENCRYPT=${ENABLE_LETSENCRYPT}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

JICOFO_AUTH_USER=focus
JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}

JVB_AUTH_USER=jvb
JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}

HTTP_PORT=80
HTTPS_PORT=443
