apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jibri
  name: jibri
spec:
  selector:
    matchLabels:
      service: jibri
  replicas: {{ .Values.jibri.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        service: jibri
    spec:
      {{- with .Values.jibri.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.jibri.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jibri.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: ENABLE_RECORDING
          value: "1"
        - name: XMPP_SERVER
          value: prosody.{{ .Release.Namespace }}.svc.cluster.local
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: JIBRI_RECORDER_USER
          value: focus
        - name: JIBRI_RECORDER_PASSWORD
          value: some-secure-passw0rd
        - name: JIBRI_XMPP_USER
          value: focus
        - name: JIBRI_XMPP_PASSWORD
          value: some-secure-passw0rd
        - name: JIBRI_BREWERY_MUC
          value: jibbrewery
        - name: JIBRI_RECORDING_DIR
          value: /data
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: TZ
          value: Europe/Paris
        image: jitsi/jibri
        imagePullPolicy: Always
        name: jibri
        resources:
          {{- toYaml .Values.jibri.resources | nindent 12 }}
      restartPolicy: Always
