apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: prosody
  name: prosody
spec:
  selector:
    matchLabels:
      service: prosody
  replicas: {{ .Values.jvb.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: prosody
    spec:
      {{- with .Values.prosody.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.prosody.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prosody.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: JICOFO_COMPONENT_SECRET
          value: some-secure-s3cret
        - name: JVB_COMPONENT_SECRET
          value: some-secure-s3cret
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JICOFO_AUTH_PASSWORD
          value: some-secure-passw0rd
        - name: JVB_AUTH_USER
          value: jvb
        - name: JVB_AUTH_PASSWORD
          value: some-secure-passw0rd
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: TZ
          value: Europe/Paris
      {{- with .Values.prosody.env }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
        image: jitsi/prosody
        imagePullPolicy: Always
        name: prosody
        ports:
        - containerPort: 5222
        - containerPort: 5280
        - containerPort: 5347
        resources:
          {{- toYaml .Values.prosody.resources | nindent 12 }}
      restartPolicy: Always
