apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
  name: web
spec:
  selector:
    matchLabels:
      service: web
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        service: web
    spec:
      {{- with .Values.web.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: JICOFO_AUTH_USER
          value: focus
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://prosody.{{ .Release.Namespace }}.svc.cluster.local:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          value: Europe/Paris
      {{- with .Values.web.env }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
        image: jitsi/web
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          {{- toYaml .Values.web.resources | nindent 12 }}
      restartPolicy: Always
