global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "alloy"
    static_configs:
      - targets: [ 'alloy:12345' ]

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'prosody'
    static_configs:
      - targets: [ 'prosody:5280' ]

  - job_name: 'jvb'
    static_configs:
      - targets: [ 'jvb:8080' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
