#!/bin/bash

# renew cert
certbot-auto renew \
  --no-self-upgrade \
  -n \
  --webroot \
  --webroot-path /var/www/letsencrypt \
  >> /config/le-renew.log

# start nginx
s6-svc -h /var/run/s6/services/nginx
