{
 "title": "Jicofo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jicofo Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"jitsi-jicofo\"}"
    }
   ]
  },
  {
   "title": "Jicofo Log Levels Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (\n  rate({service_name=\"jitsi-jicofo\"} | line_format \"{{.log}}\" | logfmt | pattern \"[<_>] <_level>: <_>\"[5m])\n)",
     "legendFormat": "Level: {{level}}"
    }
   ]
  },
  {
   "title": "Jicofo Log Levels Bar Chart",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level, attrs_service) (\n  rate({service_name=\"jitsi-jicofo\"} | line_format \"{{.message}}\" | logfmt | pattern \"[<_>] <level>#<attrs_service>: <_>\"[5m]))",
     "legendFormat": "Level: {{level}}"
    }
   ]
  },
  {
   "title": "Jicofo Total Rate of ERROR Logs Aggregated by Code File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (codefile) (\n    rate({service_name=\"jitsi-jicofo\"} | level=\"ERROR\" | line_format \"{{.message}}\" | logfmt | pattern \"[<_>] <level>#<attrs_service>: <_>\"[5m]))"
    }
   ]
  },
  {
   "title": "Jicofo Number of Conference Requests",
   "type": "timeseries",
   "description": "This panel shows the number of conference requests over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"jitsi-jicofo\"} |= \"Conference request\" [1m])"
    }
   ]
  },
  {
   "title": "Jicofo Total Counts of Member Left, Terminating, Removed Participant",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"jitsi-jicofo\"} |~ \"Member left|Terminating|Removed participant\" [1m]))"
    }
   ]
  }
 ]
}