{
 "title": "JVB & Jicofo Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Health Checks / Up", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVB Health Check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jitsi_jvb_healthy", "legendFormat": "JVB Health" }
   ]
  },
  {
   "title": "JVB Stress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 1 },
   "targets": [
    { "expr": "jitsi_jvb_stress", "legendFormat": "__auto" }
   ]
  },
  { "title": "JVB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "JVB Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "jitsi_jvb_current_endpoints", "legendFormat": "Current Endpoints" },
    { "expr": "jitsi_jvb_endpoints_inactive", "legendFormat": "Inactive Endpoints" },
    { "expr": "jitsi_jvb_endpoints_total", "legendFormat": "Total Endpoints" }
   ]
  },
  {
   "title": "Endpoints Sending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "jitsi_jvb_endpoints_sending_audio",
     "legendFormat": "Audio"
    },
    {
     "expr": "jitsi_jvb_endpoints_sending_video",
     "legendFormat": "Video"
    }
   ]
  },
  { "title": "Participants and conferences", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Participants per Bridge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "jitsi_jicofo_participants_current/jitsi_jicofo_bridge_selector_bridge_count_operational",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Restarts Requested",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "jitsi_jicofo_participants_restart_requested_created",
     "legendFormat": "Restart Request Created"
    },
    {
     "expr": "jitsi_jicofo_participants_restart_requested_total",
     "legendFormat": "Restart total"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jitsi_jvb_largest_conference", "legendFormat": "JVB Largest Conference" },
    {
     "expr": "jitsi_jicofo_largest_conference",
     "legendFormat": "Jicofo Largest Conferences"
    }
   ]
  },
  {
   "title": "Count of Conferences",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jitsi_jvb_conferences", "legendFormat": "JVB Conferences" },
    { "expr": "jitsi_jicofo_conferences", "legendFormat": "Jicofo Conferences" }
   ]
  },
  {
   "title": "Participants",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jitsi_jicofo_participants_current",
     "legendFormat": "Current Participants"
    },
    {
     "expr": "jitsi_jicofo_participants_total",
     "legendFormat": "Total Participants"
    }
   ]
  },
  {
   "title": "Count of Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "jitsi_jvb_thread_count", "legendFormat": "JVB Threads" },
    { "expr": "jitsi_jicofo_threads", "legendFormat": "Jicofo Threads" },
    { "expr": "thread", "legendFormat": "__auto" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "JVM GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "jitsi_jvb_jvm_gc_count", "legendFormat": "GC count" }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "jitsi_jvb_jvm_gc_time", "legendFormat": "GC Time" }
   ]
  },
  {
   "title": "Open FD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "jitsi_jvb_jvm_open_fd_count", "legendFormat": "Open FD Count" }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "JVB Packets Received Created",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "jitsi_jvb_packets_received_created",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "JVB Packets Sent Created",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "jitsi_jvb_packets_sent_created", "legendFormat": "Packets Sent" }
   ]
  },
  {
   "title": "Relay Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "jitsi_jvb_relay_bytes_received_created",
     "legendFormat": "Relay Packets Received Created"
    }
   ]
  },
  {
   "title": "Relay Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "jitsi_jvb_relay_bytes_sent_created",
     "legendFormat": "Relay Packets Sent Created"
    }
   ]
  },
  {
   "title": "Round Trip Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "jitsi_jvb_average_rtt", "legendFormat": "RTT" }
   ]
  }
 ]
}