{
 "title": "Prosody Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Session Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Smacks Sessions started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(prosody_mod_smacks__sessions_started_total[5m]))",
     "legendFormat": "Smacks Sessions"
    }
   ]
  },
  {
   "title": "Session Resumption Expired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(prosody_mod_smacks__session_resumption_expired_total)",
     "legendFormat": "Session Resumption Expired"
    }
   ]
  },
  {
   "title": "Bosh Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(prosody_mod_bosh__active_sessions)",
     "legendFormat": "Bosh active sessions"
    }
   ]
  },
  {
   "title": "C2S Connections by IP Family",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(prosody_mod_c2s__connections) by (ip_family)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Stanza Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TX Queued Stanzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(prosody_mod_smacks__tx_queued_stanzas_total)",
     "legendFormat": "TX Queued Stanzas"
    }
   ]
  },
  {
   "title": "Dropped Stanzas Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(prosody_mod_smacks__tx_dropped_stanzas_count[5m]))",
     "legendFormat": "Rate of Dropped Stanzas"
    }
   ]
  },
  { "title": "Processing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Processing time Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(prosody_stats_processing_seconds_sum[5m]))*1000000",
     "legendFormat": "Processing in microsecond"
    }
   ]
  },
  {
   "title": "Processing time Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(prosody_stats_processing_seconds_bucket[5m])) by (le))",
     "legendFormat": "Processing"
    }
   ]
  },
  { "title": "Room Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Room Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(prosody_mod_muc__room_hit_total{host!~\"internal-muc.*\"}) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live MUC Rooms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prosody_mod_muc__live_room{host!~\"internal-muc.*\"})by(host)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MUC Room Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(prosody_mod_muc__room_miss_total{host!~\"internal-muc.*\"})by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Bad Bosh Session IDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(prosody_mod_bosh__bad_sid_total)",
     "legendFormat": "Bad Bosh Sessions"
    }
   ]
  },
  {
   "title": "New Bosh SIDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(prosody_mod_bosh__new_sid_total)",
     "legendFormat": "New Bosh"
    }
   ]
  }
 ]
}