{
 "title": "rtcstats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rtcstats_session_count", "legendFormat": "__auto" },
    { "expr": "rtcstats_session_error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Websocket Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rtcstats_websocket_connections", "legendFormat": "__auto" },
    {
     "expr": "rtcstats_websocket_connection_error",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dump Size Bytes Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rtcstats_dump_size_bytes_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rtcstats_disk_queue_size", "legendFormat": "__auto" }
   ]
  }
 ]
}