#!/usr/bin/with-contenv bash

# TODO Fix this for OpenShift
# we have to set it, otherwise chrome won't find ~/.asoundrc file
HOME=/home/jibri

DAEMON=/opt/jitsi/jibri/launch.sh
exec /bin/bash -c "exec $DAEMON"

