#!/usr/bin/with-contenv bash

if [[ -z $JICOFO_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: Jicofo auth password must be set'
    exit 1
fi

OLD_JICOFO_AUTH_PASSWORD=passw0rd
if [[ "$JICOFO_AUTH_PASSWORD" == "$OLD_JICOFO_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: Jicofo auth password must be changed, check the README'
    exit 1
fi

tpl /defaults/jicofo.conf > /config/jicofo.conf

if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi

chown -R jicofo:jitsi /config
