name: CI Test Build

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./base
          tags: |
            jitsi/base:latest
          build-args: |
            JITSI_RELEASE=unstable

  base-java:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./base-java
          tags: |
            jitsi/base-java:latest

  jibri:
    runs-on: ubuntu-latest
    needs: base-java
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./jibri
          tags: |
            jitsi/jibri:latest

  jicofo:
    runs-on: ubuntu-latest
    needs: base-java
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./jicofo
          tags: |
            jitsi/jicofo:latest

  jigasi:
    runs-on: ubuntu-latest
    needs: base-java
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./jigasi
          tags: |
            jitsi/jigasi:latest

  jvb:
    runs-on: ubuntu-latest
    needs: base-java
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./jvb
          tags: |
            jitsi/jvb:latest

  prosody:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./prosody
          tags: |
            jitsi/prosody:latest

  web:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./web
          tags: |
            jitsi/web:latest
