name: Unstable Build

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      base: unstable
      date: unstable-${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%F)"

  base:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./base
          tags: |
            ${{ secrets.JITSI_REPO }}/base:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/base:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_RELEASE=unstable

  base-java:
    runs-on: ubuntu-latest
    needs: [version, base]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./base-java
          tags: |
            ${{ secrets.JITSI_REPO }}/base-java:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/base-java:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  jibri:
    runs-on: ubuntu-latest
    needs: [version,base-java]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./jibri
          tags: |
            ${{ secrets.JITSI_REPO }}/jibri:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/jibri:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  jicofo:
    runs-on: ubuntu-latest
    needs: [version,base-java]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./jicofo
          tags: |
            ${{ secrets.JITSI_REPO }}/jicofo:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/jicofo:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  jigasi:
    runs-on: ubuntu-latest
    needs: [version,base-java]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./jigasi
          tags: |
            ${{ secrets.JITSI_REPO }}/jigasi:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/jigasi:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  jvb:
    runs-on: ubuntu-latest
    needs: [version,base-java]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./jvb
          tags: |
            ${{ secrets.JITSI_REPO }}/jvb:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/jvb:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  prosody:
    runs-on: ubuntu-latest
    needs: [version,base]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./prosody
          tags: |
            ${{ secrets.JITSI_REPO }}/prosody:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/prosody:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}

  web:
    runs-on: ubuntu-latest
    needs: [version,base]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./web
          tags: |
            ${{ secrets.JITSI_REPO }}/web:${{ needs.version.outputs.base }}
            ${{ secrets.JITSI_REPO }}/web:${{ needs.version.outputs.date }}
          build-args: |
            JITSI_REPO=${{ secrets.JITSI_REPO }}
            BASE_TAG=${{ needs.version.outputs.base }}